import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router';
import { useTheme } from '../context/ThemeContext';
import { useAuth } from '../context/AuthContext';
import { ThemePreview, ColorSwatches } from '../components/ui/ThemePreview';
import {
  ColorPalette,
  DEFAULT_LIGHT_COLORS,
  DEFAULT_DARK_COLORS,
  COLOR_LABELS,
  COLOR_GROUPS,
  isValidHex,
  sanitizeHex,
  isGoodContrast,
  suggestPalettes,
  autoGenerateDarkFromLight,
  autoGenerateLightFromDark,
  PaletteSuggestion,
} from '../utils/colorUtils';

interface EditorNotification {
  id: string;
  message: string;
  type: 'success' | 'info' | 'error';
}
import {
  ArrowLeft,
  Palette,
  Sun,
  Moon,
  Link2,
  Unlink2,
  RotateCcw,
  Save,
  Trash2,
  Upload,
  Sparkles,
  Eye,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Leaf,
  Waves,
  Sunset,
  Trees,
  Briefcase,
  Flower,
  Flame,
  Wind,
  Sprout,
  Target,
  Shuffle,
  Layers,
  Triangle,
  RefreshCcw,
  Columns,
  Type,
  CheckCircle2,
} from 'lucide-react';

export function ThemeCustomizer() {
  const navigate = useNavigate();
  const { user } = useAuth();
    const {
    theme,
    applyCustomColors,
    resetToDefault,
    savedThemes,
    saveTheme,
    deleteTheme,
    loadTheme,
    isCustomThemeActive,
    customLightColors,
    customDarkColors,
  } = useTheme();

  // Redirigir si no es admin
  useEffect(() => {
    if (user && user.roleId !== 1 && user.roleId !== 2) {
      navigate('/settings');
    }
  }, [user, navigate]);

  // --- Estado del editor ---
  const [editLight, setEditLight] = useState<ColorPalette>(
    customLightColors || DEFAULT_LIGHT_COLORS
  );
  const [editDark, setEditDark] = useState<ColorPalette>(
    customDarkColors || DEFAULT_DARK_COLORS
  );
  const [linkedMode, setLinkedMode] = useState(false); // editar por separado por defecto
  const [editingMode, setEditingMode] = useState<'light' | 'dark'>(theme);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [saveThemeName, setSaveThemeName] = useState('');
  const [showSuggestions, setShowSuggestions] = useState(false);
  const [suggestionBaseColor, _setSuggestionBaseColor] = useState(() => {
    try {
      const saved = localStorage.getItem('agro-base-color');
      return saved || '#10b981';
    } catch { return '#10b981'; }
  });
  // Wrapper: persiste automáticamente al cambiar
  const setSuggestionBaseColor = (color: string) => {
    _setSuggestionBaseColor(color);
    try { localStorage.setItem('agro-base-color', color); } catch {}
  };
  const [suggestions, setSuggestions] = useState<PaletteSuggestion[]>([]);
  const [showSavedThemes, setShowSavedThemes] = useState(true);
  const [confirmReset, setConfirmReset] = useState(false);
  const [confirmDeleteId, setConfirmDeleteId] = useState<string | null>(null);
  const [hasChanges, setHasChanges] = useState(false);
  const [appliedLight, setAppliedLight] = useState<string | null>(null);
  const [appliedDark, setAppliedDark] = useState<string | null>(null);
  const [preLinkSnapshot, setPreLinkSnapshot] = useState<{ 
    light: ColorPalette, 
    dark: ColorPalette,
    appliedLight: string | null,
    appliedDark: string | null
  } | null>(null);

  const [notifications, setNotifications] = useState<EditorNotification[]>([]);
  const [showExitConfirm, setShowExitConfirm] = useState(false);

  const addNotification = (message: string, type: 'success' | 'info' | 'error' = 'success') => {
    const id = Math.random().toString(36).substring(2, 9);
    setNotifications(prev => [...prev, { id, message, type }]);
    setTimeout(() => {
      setNotifications(prev => prev.filter(n => n.id !== id));
    }, 3000);
  };

  // Colores actuales del modo que se está editando
  const currentEditColors = editingMode === 'light' ? editLight : editDark;
  const setCurrentEditColors = editingMode === 'light' ? setEditLight : setEditDark;

  // Track changes
  useEffect(() => {
    const origLight = customLightColors || DEFAULT_LIGHT_COLORS;
    const origDark = customDarkColors || DEFAULT_DARK_COLORS;
    const changed =
      JSON.stringify(editLight) !== JSON.stringify(origLight) ||
      JSON.stringify(editDark) !== JSON.stringify(origDark);
    setHasChanges(changed);
  }, [editLight, editDark, customLightColors, customDarkColors]);



  // --- Handlers ---
  const handleColorChange = (key: keyof ColorPalette, value: string) => {
    const sanitized = sanitizeHex(value);

    // Actualizar el modo actual
    const updated = { ...currentEditColors, [key]: sanitized };
    setCurrentEditColors(updated);

    // Si está en modo enlazado, generar contraparte automáticamente
    if (linkedMode) {
      if (editingMode === 'light') {
        setEditDark(autoGenerateDarkFromLight(updated));
      } else {
        setEditLight(autoGenerateLightFromDark(updated));
      }
    }
    
    // Limpiar el indicador de selección solo para el modo que ha cambiado
    if (editingMode === 'light') setAppliedLight(null);
    else setAppliedDark(null);
  };

  const handleToggleLinkedMode = () => {
    const nextMode = !linkedMode;
    
    if (nextMode) {
      // --- ACTIVAR ENLACE (UNIFICAR) ---
      // 1. Guardar backup de los colores actuales e indicadores de selección
      setPreLinkSnapshot({ 
        light: editLight, 
        dark: editDark,
        appliedLight: appliedLight,
        appliedDark: appliedDark
      });
      
      // 2. Unificar basados en el modo actual
      if (editingMode === 'light') {
        const generatedDark = autoGenerateDarkFromLight(editLight);
        setEditDark(generatedDark);
        // Sincronizar indicadores de selección si aplica
        setAppliedDark(appliedLight);
      } else {
        const generatedLight = autoGenerateLightFromDark(editDark);
        setEditLight(generatedLight);
        // Sincronizar indicadores de selección si aplica
        setAppliedLight(appliedDark);
      }
    } else {
      // --- DESACTIVAR ENLACE (RESTAURAR) ---
      // Si tenemos un backup previo, restaurarlo para recuperar los temas independientes originales
      if (preLinkSnapshot) {
        setEditLight(preLinkSnapshot.light);
        setEditDark(preLinkSnapshot.dark);
        setAppliedLight(preLinkSnapshot.appliedLight);
        setAppliedDark(preLinkSnapshot.appliedDark);
        setPreLinkSnapshot(null);
      }
    }
    
    setLinkedMode(nextMode);
  };

  const handleResetSingleColor = (key: keyof ColorPalette) => {
    const defaults = editingMode === 'light' ? DEFAULT_LIGHT_COLORS : DEFAULT_DARK_COLORS;
    handleColorChange(key, defaults[key]);
  };

  const handleApply = () => {
    applyCustomColors(editLight, editDark);
    setHasChanges(false);
    addNotification('¡Cambios aplicados con éxito! La interfaz se ha actualizado.', 'success');
  };

  const handleReset = () => {
    resetToDefault();
    setEditLight(DEFAULT_LIGHT_COLORS);
    setEditDark(DEFAULT_DARK_COLORS);
    setSuggestionBaseColor('#10b981');
    localStorage.removeItem('agro-base-color');
    setConfirmReset(false);
    setHasChanges(false);
    setAppliedLight(null);
    setAppliedDark(null);
    addNotification('Se han restaurado los colores predeterminados del sistema.', 'info');
  };

  const handleSave = () => {
    if (saveThemeName.trim()) {
      const name = saveThemeName.trim();
      saveTheme(name, editLight, editDark, suggestionBaseColor);
      setSaveThemeName('');
      setShowSaveModal(false);
      addNotification(`El tema "${name}" ha sido guardado correctamente.`, 'success');
    }
  };

  const handleDeleteTheme = (id: string) => {
    deleteTheme(id);
    setConfirmDeleteId(null);
    addNotification('Tema eliminado de la biblioteca.', 'info');
  };

  const handleLoadTheme = (id: string) => {
    loadTheme(id);
    const found = savedThemes.find(t => t.id === id);
    if (found) {
      setEditLight(found.lightColors);
      setEditDark(found.darkColors);
      if (found.baseColor) {
        setSuggestionBaseColor(found.baseColor);
      }
      setAppliedLight(null);
      setAppliedDark(null);
      addNotification('Tema cargado en el editor.', 'success');
    }
  };

  const handleGenerateSuggestions = () => {
    const palettes = suggestPalettes(suggestionBaseColor);
    setSuggestions(palettes);
    setShowSuggestions(true);
  };

  // --- Mapeo de iconos para temas y grupos ---
  const getThemeIcon = (name: string) => {
    const icons: Record<string, any> = {
      'Colores Principales': Palette,
      'Colores de Texto': Type,
      'Colores de Estados': CheckCircle2,
      'Base Directa': Target,
      'Complementaria': RefreshCcw,
      'Análoga': Layers,
      'Triádica': Triangle,
      'Variación Aleatoria': Shuffle,
      'Split Complementaria': Columns,
      'Naturaleza': Leaf,
      'Océano': Waves,
      'Atardecer': Sunset,
      'Bosque': Trees,
      'Corporativo': Briefcase,
      'Lavanda': Flower,
      'Volcán': Flame,
      'Otoño': Wind,
      'Primavera': Sprout,
      'Tropical': Sun,
      'Medianoche': Moon,
      'Solar': Sun,
    };
    const Icon = icons[name] || Palette;
    return <Icon size={16} style={{ color: 'var(--accent)' }} />;
  };

    const handleApplySuggestion = (suggestion: PaletteSuggestion) => {
    if (linkedMode) {
      setEditLight(suggestion.light);
      setEditDark(suggestion.dark);
      setAppliedLight(suggestion.name);
      setAppliedDark(suggestion.name);
    } else {
      // Solo aplicar al modo que se está editando actualmente
      if (editingMode === 'light') {
        setEditLight(suggestion.light);
        setAppliedLight(suggestion.name);
      } else {
        setEditDark(suggestion.dark);
        setAppliedDark(suggestion.name);
      }
    }
    setHasChanges(true);
  };

  const handleCancel = () => {
    if (hasChanges) {
      setShowExitConfirm(true);
    } else {
      navigate('/settings');
    }
  };

  // ---- Estilos ----
  const cardStyle: React.CSSProperties = {
    backgroundColor: 'var(--card)',
    borderRadius: '16px',
    border: '1px solid var(--border)',
    padding: '24px',
    boxShadow: '0 4px 6px var(--shadow)',
  };

  const btnPrimary: React.CSSProperties = {
    backgroundColor: 'var(--accent)',
    color: '#fff',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    transition: 'all 0.2s',
  };

  const btnOutline: React.CSSProperties = {
    backgroundColor: 'transparent',
    color: 'var(--text-main)',
    border: '1px solid var(--border)',
    padding: '10px 20px',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    transition: 'all 0.2s',
  };

  const btnDanger: React.CSSProperties = {
    backgroundColor: 'var(--error-red)',
    color: '#fff',
    border: 'none',
    padding: '10px 20px',
    borderRadius: '10px',
    fontWeight: 600,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '14px',
    transition: 'all 0.2s',
  };

  return (
    <div style={{ maxWidth: '1400px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <button
            onClick={handleCancel}
            style={{
              ...btnOutline,
              padding: '8px',
              borderRadius: '8px',
            }}
          >
            <ArrowLeft size={20} />
          </button>
          <div>
            <h1 className="text-3xl font-bold" style={{ color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Palette size={28} style={{ color: 'var(--accent)' }} />
              Personalización de Colores
            </h1>
            <p className="text-sm mt-1" style={{ color: 'var(--text-sec)' }}>
              Edita los colores de la aplicación en tiempo real
              {isCustomThemeActive && (
                <span style={{
                  marginLeft: '8px',
                  padding: '2px 8px',
                  borderRadius: '9999px',
                  backgroundColor: 'var(--accent)',
                  color: '#fff',
                  fontSize: '11px',
                  fontWeight: 600,
                }}>
                  Tema personalizado activo
                </span>
              )}
            </p>
          </div>
        </div>
      </div>

      {/* Control Bar */}
      <div style={{ ...cardStyle, marginBottom: '20px', padding: '16px 24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '12px' }}>
          {/* Toggle Linked/Unlinked */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <span className="text-sm font-medium" style={{ color: 'var(--text-sec)' }}>
              Modos:
            </span>
            <button
              onClick={handleToggleLinkedMode}
              style={{
                ...btnOutline,
                padding: '6px 14px',
                fontSize: '13px',
                backgroundColor: linkedMode ? 'var(--accent)' : 'transparent',
                color: linkedMode ? '#fff' : 'var(--text-main)',
                borderColor: linkedMode ? 'var(--accent)' : 'var(--border)',
              }}
            >
              {linkedMode ? <Link2 size={16} /> : <Unlink2 size={16} />}
              {linkedMode ? 'Enlazados' : 'Separados'}
            </button>
            <span className="text-xs" style={{ color: 'var(--text-sec)', maxWidth: '250px' }}>
              {linkedMode
                ? 'Cambiar un color genera automáticamente su contraparte'
                : 'Edita cada modo independientemente'}
            </span>
          </div>

          {/* Mode selector */}
          <div style={{ display: 'flex', gap: '6px' }}>
            <button
              onClick={() => setEditingMode('light')}
              style={{
                ...btnOutline,
                padding: '6px 14px',
                fontSize: '13px',
                backgroundColor: editingMode === 'light' ? 'var(--primary)' : 'transparent',
                color: editingMode === 'light' ? '#fff' : 'var(--text-main)',
                borderColor: editingMode === 'light' ? 'var(--primary)' : 'var(--border)',
              }}
            >
              <Sun size={16} />
              Claro
            </button>
            <button
              onClick={() => setEditingMode('dark')}
              style={{
                ...btnOutline,
                padding: '6px 14px',
                fontSize: '13px',
                backgroundColor: editingMode === 'dark' ? 'var(--primary)' : 'transparent',
                color: editingMode === 'dark' ? '#fff' : 'var(--text-main)',
                borderColor: editingMode === 'dark' ? 'var(--primary)' : 'var(--border)',
              }}
            >
              <Moon size={16} />
              Oscuro
            </button>
          </div>
        </div>
      </div>

      {/* Main Layout: Editor + Preview */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', alignItems: 'start' }}>
        {/* Left: Color Editor */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
          {/* Suggestion Generator */}
          <div style={cardStyle}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' }}>
              <Sparkles size={20} style={{ color: 'var(--accent)' }} />
              <h3 className="font-semibold" style={{ color: 'var(--text-main)' }}>
                Sugeridor de Paletas
              </h3>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
              <label className="text-sm" style={{ color: 'var(--text-sec)' }}>
                Color base:
              </label>
              <div style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
                <input
                  type="color"
                  value={suggestionBaseColor}
                  onChange={e => setSuggestionBaseColor(e.target.value)}
                  style={{
                    width: '36px',
                    height: '36px',
                    border: 'none',
                    borderRadius: '8px',
                    cursor: 'pointer',
                    padding: 0,
                  }}
                />
                <input
                  type="text"
                  value={suggestionBaseColor}
                  onChange={e => setSuggestionBaseColor(sanitizeHex(e.target.value))}
                  style={{
                    width: '90px',
                    padding: '6px 10px',
                    borderRadius: '6px',
                    border: '1px solid var(--border)',
                    backgroundColor: 'var(--bg)',
                    color: 'var(--text-main)',
                    fontSize: '13px',
                    fontFamily: 'monospace',
                  }}
                />
              </div>
              <button onClick={handleGenerateSuggestions} style={{ ...btnPrimary, padding: '8px 16px', fontSize: '13px' }}>
                <Sparkles size={14} />
                Generar Sugerencias
              </button>
            </div>

            {/* Suggestions display */}
            {showSuggestions && suggestions.length > 0 && (
              <div style={{ marginTop: '16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {suggestions.map((s, i) => {
                  const isApplied = editingMode === 'light' ? appliedLight === s.name : appliedDark === s.name;
                  return (
                    <div
                      key={i}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'space-between',
                        padding: '10px 14px',
                        borderRadius: '10px',
                        border: isApplied ? '2px solid var(--accent)' : '1px solid var(--border)',
                        backgroundColor: isApplied ? 'rgba(var(--accent-rgb, 16, 185, 129), 0.05)' : 'var(--card)',
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                        boxShadow: isApplied ? '0 0 0 1px var(--accent)' : 'none',
                      }}
                      onMouseEnter={e => {
                        if (!isApplied) {
                          (e.currentTarget as HTMLElement).style.borderColor = 'var(--accent)';
                        }
                        (e.currentTarget as HTMLElement).style.transform = 'translateX(4px)';
                      }}
                      onMouseLeave={e => {
                        if (!isApplied) {
                          (e.currentTarget as HTMLElement).style.borderColor = 'var(--border)';
                        }
                        (e.currentTarget as HTMLElement).style.transform = 'translateX(0)';
                      }}
                    >
                      <div style={{ display: 'flex', gap: '12px', alignItems: 'flex-start', flex: 1 }}>
                        <div style={{ marginTop: '2px' }}>
                          {getThemeIcon(s.name)}
                        </div>
                        <div style={{ flex: 1 }}>
                          <div className="font-semibold text-sm" style={{ color: 'var(--text-main)', display: 'flex', alignItems: 'center', gap: '8px' }}>
                            {s.name}
                            {isApplied && (
                              <span style={{ 
                                display: 'inline-flex', 
                                alignItems: 'center', 
                                gap: '4px', 
                                color: 'var(--accent)', 
                                fontSize: '10px',
                                fontWeight: 700,
                                textTransform: 'uppercase'
                              }}>
                                <Check size={12} />
                                Seleccionado
                              </span>
                            )}
                          </div>
                          <div className="text-xs" style={{ color: 'var(--text-sec)' }}>
                            {s.description}
                          </div>
                          <div style={{ marginTop: '6px' }}>
                            <ColorSwatches colors={editingMode === 'light' ? s.light : s.dark} size={16} />
                          </div>
                        </div>
                      </div>
                      <div style={{ display: 'flex', gap: '8px' }}>
                        <button
                          onClick={() => handleApplySuggestion(s)}
                          style={{ 
                            ...btnPrimary, 
                            padding: '6px 16px', 
                            fontSize: '13px',
                            backgroundColor: isApplied ? 'var(--text-sec)' : 'var(--accent)',
                            opacity: isApplied ? 0.8 : 1
                          }}
                        >
                          <Check size={14} />
                          {isApplied ? 'Aplicado' : 'Usar'}
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Color groups */}
          {COLOR_GROUPS.map((group) => (
            <div key={group.title} style={cardStyle}>
              <h3 className="font-semibold mb-4" style={{ color: 'var(--text-main)', fontSize: '15px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                {getThemeIcon(group.title)}
                {group.title}
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {group.keys.map((key) => {
                  const value = currentEditColors[key];
                  const isShadow = key === 'shadow';
                  const defaultVal = (editingMode === 'light' ? DEFAULT_LIGHT_COLORS : DEFAULT_DARK_COLORS)[key];
                  const isModified = value !== defaultVal;

                  // Contraste check para colores de texto
                  const contrastBg = currentEditColors.bg;
                  const showContrast = ['textMain', 'textSec', 'successText', 'warningText', 'errorText'].includes(key);
                  const contrastGood = showContrast && isValidHex(value) && isValidHex(contrastBg) ? isGoodContrast(value, contrastBg) : null;

                  // Para colores de estado con fondo, verificar contra texto
                  const showBgContrast = ['successBg', 'warningBg', 'errorBg'].includes(key);
                  const bgContrastKey = key.replace('Bg', 'Text') as keyof ColorPalette;
                  const bgContrastGood = showBgContrast && isValidHex(value) && isValidHex(currentEditColors[bgContrastKey])
                    ? isGoodContrast(currentEditColors[bgContrastKey], value)
                    : null;

                  return (
                    <div
                      key={key}
                      style={{
                        display: 'flex',
                        alignItems: 'center',
                        gap: '10px',
                        padding: '8px 12px',
                        borderRadius: '8px',
                        backgroundColor: isModified ? 'var(--bg)' : 'transparent',
                        border: isModified ? '1px solid var(--accent)' : '1px solid transparent',
                        transition: 'all 0.2s',
                      }}
                    >
                      {/* Color swatch / picker */}
                      {!isShadow && (
                        <input
                          type="color"
                          value={isValidHex(value) ? value : '#000000'}
                          onChange={e => handleColorChange(key, e.target.value)}
                          style={{
                            width: '32px',
                            height: '32px',
                            border: 'none',
                            borderRadius: '6px',
                            cursor: 'pointer',
                            padding: 0,
                            flexShrink: 0,
                          }}
                        />
                      )}
                      {isShadow && (
                        <div
                          style={{
                            width: '32px',
                            height: '32px',
                            borderRadius: '6px',
                            background: 'linear-gradient(135deg, #ddd, #888)',
                            flexShrink: 0,
                          }}
                        />
                      )}

                      {/* Label */}
                      <div style={{ flex: 1, minWidth: 0 }}>
                        <div className="text-sm font-medium" style={{ color: 'var(--text-main)' }}>
                          {COLOR_LABELS[key]}
                        </div>
                        {(contrastGood !== null) && (
                          <div className="text-xs" style={{ 
                            color: contrastGood ? 'var(--success-text)' : 'var(--error-red)',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '4px',
                            marginTop: '2px'
                          }}>
                            {contrastGood ? <Check size={12} /> : <AlertTriangle size={12} />}
                            {contrastGood ? 'Buen contraste' : 'Contraste bajo'}
                          </div>
                        )}
                        {(bgContrastGood !== null) && (
                          <div className="text-xs" style={{ 
                            color: bgContrastGood ? 'var(--success-text)' : 'var(--error-red)',
                            display: 'flex',
                            alignItems: 'center',
                            gap: '4px',
                            marginTop: '2px'
                          }}>
                            {bgContrastGood ? <Check size={12} /> : <AlertTriangle size={12} />}
                            {bgContrastGood ? 'Legible' : 'Puede ser difícil de leer'}
                          </div>
                        )}
                      </div>

                      {/* Hex input */}
                      <input
                        type="text"
                        value={value}
                        onChange={e => handleColorChange(key, e.target.value)}
                        style={{
                          width: isShadow ? '160px' : '90px',
                          padding: '5px 8px',
                          borderRadius: '6px',
                          border: '1px solid var(--border)',
                          backgroundColor: 'var(--card)',
                          color: 'var(--text-main)',
                          fontSize: '12px',
                          fontFamily: 'monospace',
                        }}
                      />

                      {/* Reset single */}
                      {isModified && !isShadow && (
                        <button
                          onClick={() => handleResetSingleColor(key)}
                          title="Restaurar predeterminado"
                          style={{
                            padding: '4px',
                            borderRadius: '4px',
                            border: 'none',
                            backgroundColor: 'transparent',
                            color: 'var(--text-sec)',
                            cursor: 'pointer',
                            flexShrink: 0,
                          }}
                        >
                          <RotateCcw size={14} />
                        </button>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Right: Preview + Actions */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', position: 'sticky', top: '20px' }}>
          {/* Preview */}
          <div style={cardStyle}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '12px' }}>
              <Eye size={18} style={{ color: 'var(--accent)' }} />
              <h3 className="font-semibold" style={{ color: 'var(--text-main)', fontSize: '15px', display: 'flex', alignItems: 'center', gap: '6px' }}>
                Vista Previa — {editingMode === 'light' ? <><Sun size={14} /> Modo Claro</> : <><Moon size={14} /> Modo Oscuro</>}
              </h3>
            </div>
            <ThemePreview 
              colors={currentEditColors} 
            />
          </div>

          {/* Opposite mode preview */}
          <div style={cardStyle}>
            <h3 className="font-semibold mb-3" style={{ color: 'var(--text-main)', fontSize: '14px' }}>
              {editingMode === 'light' ? <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Moon size={14} /> Vista Previa Oscuro</span> : <span style={{ display: 'flex', alignItems: 'center', gap: '6px' }}><Sun size={14} /> Vista Previa Claro</span>}
              {linkedMode && (
                <span className="text-xs font-normal ml-2" style={{ color: 'var(--text-sec)' }}>
                  (generado automáticamente)
                </span>
              )}
            </h3>
            <ThemePreview
              colors={editingMode === 'light' ? editDark : editLight}
              compact
            />
          </div>

          {/* Actions */}
          <div style={cardStyle}>
            <h3 className="font-semibold mb-4" style={{ color: 'var(--text-main)', fontSize: '15px' }}>
              Acciones
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
              <button
                onClick={handleApply}
                style={{ ...btnPrimary, justifyContent: 'center', opacity: hasChanges ? 1 : 0.6 }}
                disabled={!hasChanges}
              >
                <Check size={18} />
                Aplicar Cambios
              </button>
              <button
                onClick={() => setShowSaveModal(true)}
                style={{ ...btnOutline, justifyContent: 'center', borderColor: 'var(--accent)', color: 'var(--accent)' }}
              >
                <Save size={18} />
                Guardar Combinación
              </button>
              {!confirmReset ? (
                <button
                  onClick={() => setConfirmReset(true)}
                  style={{ ...btnOutline, justifyContent: 'center', color: 'var(--error-red)', borderColor: 'var(--error-red)' }}
                >
                  <RotateCcw size={18} />
                  Restaurar Predeterminado
                </button>
              ) : (
                <div style={{ display: 'flex', gap: '8px' }}>
                  <button onClick={handleReset} style={{ ...btnDanger, flex: 1, justifyContent: 'center' }}>
                    Confirmar Reset
                  </button>
                  <button onClick={() => setConfirmReset(false)} style={{ ...btnOutline, flex: 1, justifyContent: 'center' }}>
                    Cancelar
                  </button>
                </div>
              )}
              <button onClick={handleCancel} style={{ ...btnOutline, justifyContent: 'center' }}>
                <X size={18} />
                Volver a Configuración
              </button>
            </div>
          </div>

          {/* Saved Themes */}
          <div style={cardStyle}>
            <button
              onClick={() => setShowSavedThemes(!showSavedThemes)}
              style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                width: '100%',
                background: 'none',
                border: 'none',
                cursor: 'pointer',
                padding: 0,
              }}
            >
              <h3 className="font-semibold" style={{ color: 'var(--text-main)', fontSize: '15px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                <Save size={16} />
                Temas Guardados ({savedThemes.length})
              </h3>
              {showSavedThemes ? (
                <ChevronUp size={18} style={{ color: 'var(--text-sec)' }} />
              ) : (
                <ChevronDown size={18} style={{ color: 'var(--text-sec)' }} />
              )}
            </button>

            {showSavedThemes && (
              <div style={{ marginTop: '12px' }}>
                {savedThemes.length === 0 ? (
                  <p className="text-sm" style={{ color: 'var(--text-sec)', textAlign: 'center', padding: '20px 0' }}>
                    No hay temas guardados aún. Crea tu primera combinación de colores y guárdala.
                  </p>
                ) : (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                    {savedThemes.map((st) => (
                      <div
                        key={st.id}
                        style={{
                          display: 'flex',
                          alignItems: 'center',
                          justifyContent: 'space-between',
                          padding: '10px 14px',
                          borderRadius: '10px',
                          border: '1px solid var(--border)',
                          backgroundColor: 'var(--bg)',
                        }}
                      >
                        <div>
                          <div className="font-medium text-sm" style={{ color: 'var(--text-main)' }}>
                            {st.name}
                          </div>
                          <div className="text-xs" style={{ color: 'var(--text-sec)', display: 'flex', alignItems: 'center', gap: '6px' }}>
                            {new Date(st.createdAt).toLocaleDateString('es-MX', {
                              day: 'numeric',
                              month: 'short',
                              year: 'numeric',
                            })}
                            {st.baseColor && (
                              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '3px' }}>
                                · Base:
                                <span
                                  style={{
                                    display: 'inline-block',
                                    width: '10px',
                                    height: '10px',
                                    borderRadius: '50%',
                                    backgroundColor: st.baseColor,
                                    border: '1px solid rgba(128,128,128,0.3)',
                                  }}
                                />
                                <span style={{ fontFamily: 'monospace', fontSize: '10px' }}>{st.baseColor}</span>
                              </span>
                            )}
                          </div>
                          <div style={{ marginTop: '8px', display: 'flex', gap: '12px', alignItems: 'center' }}>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }} title="Modo Claro">
                              <Sun size={12} style={{ color: 'var(--text-sec)', opacity: 0.7 }} />
                              <ColorSwatches colors={st.lightColors} size={13} />
                            </div>
                            <div style={{ width: '1px', height: '12px', backgroundColor: 'var(--border)' }} />
                            <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }} title="Modo Oscuro">
                              <Moon size={12} style={{ color: 'var(--text-sec)', opacity: 0.7 }} />
                              <ColorSwatches colors={st.darkColors} size={13} />
                            </div>
                          </div>
                        </div>
                        <div style={{ display: 'flex', gap: '6px' }}>
                          <button
                            onClick={() => handleLoadTheme(st.id)}
                            style={{
                              ...btnOutline,
                              padding: '6px 12px',
                              fontSize: '12px',
                              fontWeight: 600,
                              display: 'flex',
                              alignItems: 'center',
                              gap: '4px',
                            }}
                          >
                            <Upload size={12} />
                            Cargar
                          </button>
                          {confirmDeleteId === st.id ? (
                            <div style={{ display: 'flex', gap: '4px' }}>
                              <button
                                onClick={() => {
                                  handleDeleteTheme(st.id);
                                }}
                                style={{
                                  padding: '6px 8px',
                                  borderRadius: '6px',
                                  border: 'none',
                                  backgroundColor: 'var(--error-red)',
                                  color: '#fff',
                                  cursor: 'pointer',
                                  fontSize: '11px',
                                }}
                              >
                                Sí
                              </button>
                              <button
                                onClick={() => setConfirmDeleteId(null)}
                                style={{
                                  padding: '6px 8px',
                                  borderRadius: '6px',
                                  border: '1px solid var(--border)',
                                  backgroundColor: 'transparent',
                                  color: 'var(--text-main)',
                                  cursor: 'pointer',
                                  fontSize: '11px',
                                }}
                              >
                                No
                              </button>
                            </div>
                          ) : (
                            <button
                              onClick={() => setConfirmDeleteId(st.id)}
                              title="Eliminar tema"
                              style={{
                                padding: '6px',
                                borderRadius: '6px',
                                border: '1px solid var(--border)',
                                backgroundColor: 'transparent',
                                color: 'var(--text-sec)',
                                cursor: 'pointer',
                              }}
                            >
                              <Trash2 size={14} />
                            </button>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Save Modal */}
      {showSaveModal && (
        <div
          style={{
            position: 'fixed',
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            backgroundColor: 'rgba(0,0,0,0.5)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            zIndex: 9999,
          }}
          onClick={() => setShowSaveModal(false)}
        >
          <div
            style={{
              backgroundColor: 'var(--card)',
              borderRadius: '16px',
              padding: '28px',
              width: '480px',
              maxWidth: '90vw',
              boxShadow: '0 20px 60px rgba(0,0,0,0.3)',
            }}
            onClick={e => e.stopPropagation()}
          >
            <h2 className="text-xl font-bold mb-2" style={{ color: 'var(--text-main)' }}>
              Guardar Combinación de Colores
            </h2>
            <p className="text-sm mb-4" style={{ color: 'var(--text-sec)' }}>
              Dale un nombre memorable a esta paleta para encontrarla fácilmente después.
            </p>

            <input
              type="text"
              value={saveThemeName}
              onChange={e => setSaveThemeName(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleSave()}
              placeholder="Ej: Verde Corporativo, Modo Serio, Tema Navideño..."
              autoFocus
              style={{
                width: '100%',
                padding: '12px 16px',
                borderRadius: '10px',
                border: '1px solid var(--border)',
                backgroundColor: 'var(--bg)',
                color: 'var(--text-main)',
                fontSize: '14px',
                marginBottom: '16px',
                outline: 'none',
              }}
            />

            {/* Preview de lo que se va a guardar */}
            <div style={{ marginBottom: '16px' }}>
              <p className="text-xs font-medium mb-2" style={{ color: 'var(--text-sec)' }}>
                Vista previa:
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
                <div>
                  <p className="text-xs mb-1" style={{ color: 'var(--text-sec)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <Sun size={10} /> Claro
                  </p>
                  <ThemePreview colors={editLight} compact />
                </div>
                <div>
                  <p className="text-xs mb-1" style={{ color: 'var(--text-sec)', display: 'flex', alignItems: 'center', gap: '4px' }}>
                    <Moon size={10} /> Oscuro
                  </p>
                  <ThemePreview colors={editDark} compact />
                </div>
              </div>
            </div>

            <div style={{ display: 'flex', gap: '10px', justifyContent: 'flex-end' }}>
              <button onClick={() => setShowSaveModal(false)} style={btnOutline}>
                Cancelar
              </button>
              <button
                onClick={handleSave}
                style={{ ...btnPrimary, opacity: saveThemeName.trim() ? 1 : 0.5 }}
                disabled={!saveThemeName.trim()}
              >
                <Save size={16} />
                Guardar
              </button>
            </div>
          </div>
        </div>
      )}
      {/* Lista de Notificaciones (Toasts) */}
      <div style={{
        position: 'fixed',
        top: '24px',
        right: '24px',
        zIndex: 1000,
        display: 'flex',
        flexDirection: 'column',
        gap: '10px',
        pointerEvents: 'none',
      }}>
        {notifications.map((n) => (
          <div
            key={n.id}
            style={{
              pointerEvents: 'auto',
              minWidth: '300px',
              padding: '16px 20px',
              borderRadius: '12px',
              backgroundColor: 'var(--card)',
              borderLeft: `6px solid ${n.type === 'success' ? 'var(--accent)' : n.type === 'error' ? 'var(--error-red)' : 'var(--primary)'}`,
              boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
              display: 'flex',
              alignItems: 'center',
              gap: '12px',
              animation: 'toast-in 0.3s ease-out forwards',
              color: 'var(--text-main)',
            }}
          >
            {n.type === 'success' ? <CheckCircle2 size={20} style={{ color: 'var(--accent)' }} /> : 
             n.type === 'error' ? <AlertTriangle size={20} style={{ color: 'var(--error-red)' }} /> : 
             <Sparkles size={20} style={{ color: 'var(--primary)' }} />}
            <span style={{ fontSize: '14px', fontWeight: 500 }}>{n.message}</span>
          </div>
        ))}
        <style>
          {`
            @keyframes toast-in {
              from { transform: translateX(100%); opacity: 0; }
              to { transform: translateX(0); opacity: 1; }
            }
          `}
        </style>
      </div>

      {/* Modal Confirmación Salida */}
      {showExitConfirm && (
        <div style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          bottom: 0,
          backgroundColor: 'rgba(0,0,0,0.5)',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          zIndex: 1100,
          backdropFilter: 'blur(4px)',
        }}>
          <div style={{ ...cardStyle, width: '450px', position: 'relative' }}>
            <div style={{ textAlign: 'center', marginBottom: '24px' }}>
              <div style={{ 
                width: '64px', 
                height: '64px', 
                borderRadius: '50%', 
                backgroundColor: 'rgba(239, 68, 68, 0.1)', 
                display: 'flex', 
                alignItems: 'center', 
                justifyContent: 'center', 
                margin: '0 auto 16px' 
              }}>
                <AlertTriangle size={32} style={{ color: 'var(--error-red)' }} />
              </div>
              <h2 className="text-xl font-bold mb-2" style={{ color: 'var(--text-main)' }}>¿Abandonar el editor?</h2>
              <p style={{ color: 'var(--text-sec)', fontSize: '15px' }}>
                Tienes cambios en los colores que no han sido aplicados. Si sales ahora, se perderán permanentemente.
              </p>
            </div>
            <div style={{ display: 'flex', gap: '12px' }}>
              <button 
                onClick={() => navigate('/settings')} 
                style={{ ...btnDanger, flex: 1, justifyContent: 'center' }}
              >
                Salir sin guardar
              </button>
              <button 
                onClick={() => setShowExitConfirm(false)} 
                style={{ ...btnOutline, flex: 1, justifyContent: 'center' }}
              >
                Seguir editando
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
